---
#$ curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
#$ yum -y install nodejs

# - name: Adding Node Package
#   shell: curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
#   become: true

# - name: Installing Dependencies
#   yum:
#     name: "{{ item }}"
#     state: present
#   become: yes
#   with_items:
#      - gcc
#      - openssl-devel
#      - libyaml-devel
#      - libffi-devel
#      - readline-devel
#      - zlib-devel
#      - gdbm-devel
#      - ncurses-devel
#      - gcc-c++
#      - jq
#      - git
#      - nodejs
#      - htop
#      - sysstat
#      - autoconf
#      - patch
#      - automake
#      - libtool
#      - bison
#      - tcpdump
#      - mlocate
#      - telnet
#      - lsof
#      - strace

- name: Create App Directory
  file:
    path: /opt/node_test
    state: directory
    mode: '0755'


- name: Clone the repository
  git:
    repo: git@github.com:jefersonlemos/node.git
    dest: "{{ app.path }}"
    accept_hostkey: yes
    #key_file: "{{ homeDir }}"/id_rsa
    #branch: master
    #register: git_finished

- name: Install packages based on package.json using the npm installed with nvm v0.10.1.
  npm:
    path: "{{ app_path }}"


#start

